### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by 0x4bs3nt** [davidliaos/AutoRedditStories#3]
There eseems to be an error with the whispercpp model, it is failing to transcribe and throwing the FileNotFoundError. Is there any way we can contact through some service, I am very intersted in this project?

**Comment by davidliaos** [comment]
Sorry, didn't notice this until now. WhisperCPP is a C++ implimentation of OpenAI's Whisper model. This project is built with that in mind. Can you include what OS you're on? I have only ran this project on MacOS Ventura and Windows 10.

**Comment by 0x4bs3nt** [comment]
Hey, got it working manually, edited some code to fix it. Tbh, I don't remember what I changed and I don't have the repo anymore locally. I ran it on MacOS and Win 11 successfully after some tweaks, however I don't think it works out of the box.

**Comment by davidliaos** [comment]
There's very minor differences between the version I locally and the github repo, none that should stop it from running entirely. I would have to guess the issue lies somewhere within the Reddit API since I have not made any changes following their updated API, currently my version is sitting on like 20 GB worth of .txt files so I haven't accessed the API in at least a month.

If you're able to find the changes you made it would be nice to send in a PR, appreciate you trying my project.
